### ISSUE TITLE
Peer to Peer Code Review 2021-11-18

### ISSUE THREAD

**Issue by vechicin** [keroloussamy/Module1-Capstone#2]
# Fantastic Job Kero! 🔥 💪 ✅ 🤓 💯 
This is, by far, the best p2p code review presentation I've seen in my time at Microverse, I definitely learned some useful tools that I will put into practice for the rest of my career as a developer.

## Comments
I think it would be a good idea to include the project's logo inside the head tag that way you can see it in the browser's tab next to the title.

I found several lines of code in CSS that aren't doing anything, it would be a good idea to remove them to clean up your code, I'll link one of them so you have an idea but try looking for the other ones by yourself:

- In the _utilities.scss file, line 71, the align-items rule isn't doing anything

Once again fantastic job! 😄

**Comment by CRClothier** [comment]
Hi Kero!

Sorry about the lateness of this comment, But I totally agree with Santigo that you have done really excellent work here and it was really educational to see your thinking and strategies. 😃👍

The one thing I noticed that you could perhaps improve would be the images on the featured speakers section.  They look great on mobile and great on desktop, but when you drag the window between the two sizes the images get a little squashed.   You could perhaps solve this by adding a height property to the images that scales with the width of the page, using vw units for example.

But really that's the only small thing I noticed beyond what Santiago has already commented, so great work! ⭐️
