### ISSUE TITLE
Morning session code-review 26-11-2021

### ISSUE THREAD

**Issue by gemmen29** [keroloussamy/Module1-Capstone#3]
Good job in implementing all the requirements of the project but I have some suggestions:

1. There is a vertical scroll bar in mobile view.
2. The images of the speaker section have some problems in aspect ratio.

**Comment by williamrolando88** [comment]
Hi Kero :wave: 

Nice job on your capstone project I liked how you managed to use a combination of bootstrap and CSS, to get the best of both, your presentation looks neat:

Here I have some suggestions that could come in handy in the future:
- Here in the desktop version, you could improve the partners' section, by using png images without background color, and adjusting them a little bigger than they are now.
![Screenshot from 2021-11-26 09-29-21](https://user-images.githubusercontent.com/52635378/143597291-71e4cdde-4f10-48ae-aee5-8efd2a68d00b.png)
- Here in the script, for future references, try to avoid the usage of `innerHTML` unless it is necessary, you can achieve the same function using the native DOM manipulation tools. Here I share with you some articles to help you: [Differences between textContent and innerHTML](https://www.microfocus.com/documentation/silk-test/200/en/silktestworkbench-help-en/SILKTEST-21EEFF3F-DIFFERENCEBETWEENTEXTCONTENTSINNERTEXTINNERHTML-REF.html) and [Dangers of innerHTML](https://betterprogramming.pub/dom-manipulation-the-dangers-of-innerhtml-602f4119d905)
https://github.com/keroloussamy/Module1-Capstone/blob/2a4cefcaebc12615e19b54ee7e04caa326cf11cf/js/app.js#L47-L60
- In the menu for the mobile version, it would be great if after the nav menu opens, the menu icon will change for the closing X in the same place.
![Screenshot from 2021-11-26 09-50-12](https://user-images.githubusercontent.com/52635378/143598456-5a6cddb7-85e0-4233-ad57-336b49a1697c.png)

I hope this information will help you in the future. :smile:
